/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelAdmin;

import services.DigitalClockService;

/**
 *
 * @author ADVAN
 */
public class Absensi extends javax.swing.JPanel {
    Thread clockThread1;

    /**
     * Creates new form Absensi
     */
    public Absensi() {
        initComponents();
        thread1();
        // Atur agar jPanel11 menyusun kartu log secara vertikal ke bawah
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
        
        // Atur agar jPanel11 menyusun kartu log secara vertikal ke bawah
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
        
        // Listener saat RFID di-scan / ditekan Enter
        txtInputRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputRFIDActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRFID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAutoRefresh = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        txtInputRFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRFID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/card2.png"))); // NOI18N
        lblRFID.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(lblRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tempel kartu atau ketikan RFID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Log Scan RFID Terbaru ");

        btnAutoRefresh.setBackground(new java.awt.Color(51, 255, 153));
        btnAutoRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAutoRefresh.setText("Auto Refresh");
        btnAutoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoRefreshActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(btnAutoRefresh)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 860, 240));

        txtInputRFID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInputRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputRFIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtInputRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 390, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoRefreshActionPerformed
        // TODO add your handling code here:
        // 1. Bersihkan semua kartu log absensi dari jPanel11
        jPanel11.removeAll();
        
        // 2. Segarkan tampilan UI agar langsung terlihat kosong kembali
        jPanel11.revalidate();
        jPanel11.repaint();
        
        // 3. Kembalikan fokus kursor ke input RFID agar siap menerima scan kartu baru
        txtInputRFID.setText("");
        txtInputRFID.requestFocus();
        
        // 4. Munculkan notifikasi singkat di pojok layar (opsional)
        System.out.println("Log tampilan absensi berhasil dibersihkan.");
    }//GEN-LAST:event_btnAutoRefreshActionPerformed

    private void txtInputRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputRFIDActionPerformed
        String rfidInput = txtInputRFID.getText().trim();
        if (rfidInput.isEmpty()) return;

        try {
            // 1. Inisialisasi MahasiswaService untuk mencari data mahasiswa
            services.MahasiswaService mService = new services.MahasiswaService();
            
            // Cari data mahasiswa berdasarkan uidRfid mentah (Plain Text seperti di DB)
            objects.mahasiswa m = mService.cariMahasiswaSpesifikUID(rfidInput);
            
            if (m != null) {
                // 2. Dekripsi data NIM mahasiswa
                String nimDecrypted = util.EncryptionUtils.decrypt(m.getNimMahasiswa());
                String namaMahasiswa = m.getNama();
                
                // 3. PENETAPAN WAKTU: Cek status kehadiran secara dinamis
                java.time.LocalTime waktuSekarang = java.time.LocalTime.now();
                
                // Aturan waktu operasional (Bisa kamu sesuaikan sendiri jamnya)
                java.time.LocalTime jamMasuk = java.time.LocalTime.of(8, 0);       // Batas 08:00
                java.time.LocalTime batasTerlambat = java.time.LocalTime.of(8, 15); // Batas Toleransi 08:15
                
                String statusKehadiran = "Tepat Waktu";
                
                if (waktuSekarang.isAfter(jamMasuk) && (waktuSekarang.isBefore(batasTerlambat) || waktuSekarang.equals(batasTerlambat))) {
                    statusKehadiran = "Terlambat";
                } else if (waktuSekarang.isAfter(batasTerlambat)) {
                    statusKehadiran = "Terlambat (Sanksi)";
                }
                
                // 4. Tampilkan kartu informasi log di panel hijau UI
                appendLogAbsensi(rfidInput, namaMahasiswa, nimDecrypted, statusKehadiran);
                
                // 5. PROSES SIMPAN KE DATABASE MENGGUNAKAN LOGABSENSISERVICE BAWAANMU
                services.LogAbsensiService logService = new services.LogAbsensiService();
                
                // Ambil waktu tanggal hari ini
                java.time.LocalDateTime waktuSkrg = java.time.LocalDateTime.now();
                java.time.LocalDate tanggalSkrg = java.time.LocalDate.now();
                
                // Panggil metode bawaanmu. (Kita kirim nimDecrypted atau rfidInput ke parameter hashedUid sesuai kebutuhan pelaporanmu)
                logService.simpanLog(rfidInput, waktuSkrg, tanggalSkrg, namaMahasiswa, statusKehadiran);
                
                System.out.println("Log absensi tersimpan via LogAbsensiService untuk: " + namaMahasiswa);
                // ======================================================================
                
            } else {
                // Penanganan jika UID RFID tidak terdaftar
                appendLogAbsensi(rfidInput, "TIDAK DIKENAL", "-----", "Belum Terdaftar");
            }
            
        } catch (Exception e) {
            System.out.println("Kendala pemrosesan data tap absensi: " + e.getMessage());
            e.printStackTrace();
        }
        
        // Kosongkan form teks dan kembalikan fokus kursor
        txtInputRFID.setText("");
        txtInputRFID.requestFocus();
    }//GEN-LAST:event_txtInputRFIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRFID;
    private javax.swing.JTextField txtInputRFID;
    // End of variables declaration//GEN-END:variables
    private void thread1() {
        DigitalClockService service = new DigitalClockService(jLabel1, "EEEE, d MMMM yyyy, HH:mm:ss");
        clockThread1 = service.getThread();
        clockThread1.setName("Thread-Jam-Kiosk2");
        clockThread1.setDaemon(true);
        clockThread1.start();
    }
    
    public void appendLogAbsensi(String rfid, String nama, String nim, String status) {
        // 1. Membuat KARTU UTAMA (Card Panel)
        javax.swing.JPanel cardLog = new javax.swing.JPanel();
        cardLog.setLayout(new java.awt.GridLayout(1, 4, 10, 0)); // Membagi kartu jadi 4 kolom sejajar
        cardLog.setBackground(java.awt.Color.WHITE);
        
        // Memberikan margin jarak antar kartu dan outline border tipis membulat (Rounded)
        cardLog.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10), // Jarak luar antar kartu
                javax.swing.BorderFactory.createCompoundBorder(
                        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 1, true), // Border abu tipis
                        javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15) // Padding dalam kartu
                )
        ));
        cardLog.setMaximumSize(new java.awt.Dimension(1019, 55)); // Menyesuaikan ukuran jPanel11

        // 2. Membuat teks informasi waktu & rfid (Kolom 1)
        java.time.LocalTime now = java.time.LocalTime.now();
        String waktuAbsen = now.format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"));
        javax.swing.JLabel lblWaktu = new javax.swing.JLabel("[" + waktuAbsen + "]  RFID: " + rfid);
        lblWaktu.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        lblWaktu.setForeground(java.awt.Color.DARK_GRAY);

        // 3. Membuat teks informasi NIM (Kolom 2)
        javax.swing.JLabel lblNim = new javax.swing.JLabel("NIM: " + nim);
        lblNim.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // 4. Membuat teks informasi Nama (Kolom 3)
        javax.swing.JLabel lblNama = new javax.swing.JLabel("Nama: " + nama);
        lblNama.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // 5. Membuat status dengan warna khusus (Kolom 4)
        javax.swing.JLabel lblStatus = new javax.swing.JLabel(status, javax.swing.SwingConstants.RIGHT);
        lblStatus.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        
        // Atur warna teks status secara dinamis
        if (status.equalsIgnoreCase("Terlambat") || status.equalsIgnoreCase("Belum Terdaftar")) {
            lblStatus.setForeground(java.awt.Color.RED);
        } else {
            lblStatus.setForeground(new java.awt.Color(0, 153, 51)); // Hijau sukses
        }

        // 6. Masukkan komponen ke dalam susunan kolom kartu
        cardLog.add(lblWaktu);
        cardLog.add(lblNim);
        cardLog.add(lblNama);
        cardLog.add(lblStatus);

        // 7. Sisipkan kartu ke urutan teratas (index 0) di jPanel11
        jPanel11.add(cardLog, 0);

        // Batasi maksimal memuat 3 komponen kartu agar pas di area hijau jPanel11
        if (jPanel11.getComponentCount() > 3) {
            jPanel11.remove(jPanel11.getComponentCount() - 1);
        }

        // Segarkan layout UI
        jPanel11.revalidate();
        jPanel11.repaint();
    }
}
