/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelAdmin;

import services.DigitalClockService;

/**
 *
 * @author ADVAN
 */
public class Absensi extends javax.swing.JPanel implements swing.I18nService.I18nChangeListener {
    Thread clockThread1;

    /**
     * Creates new form Absensi
     */
    public Absensi() {
        initComponents();
        swing.I18nService.registerListener(this);    
        onLanguageChanged();
        thread1();
        // Atur agar jPanel11 menyusun kartu log secara vertikal ke bawah
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
        
        // Atur agar jPanel11 menyusun kartu log secara vertikal ke bawah
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
        
        // Listener saat RFID di-scan / ditekan Enter
        txtInputRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputRFIDActionPerformed(evt);
            }
        });
    }
    public void onLanguageChanged() {
        jLabel2.setText(swing.I18nService.get("lbl.kiosk.prompt"));
        jLabel3.setText(swing.I18nService.get("lbl.kiosk.log.title"));
        btnAutoRefresh.setText(swing.I18nService.get("btn.kiosk.refresh"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRFID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAutoRefresh = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        txtInputRFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRFID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/card2.png"))); // NOI18N
        lblRFID.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(lblRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tempel kartu atau ketikan RFID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 400, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Log Scan RFID Terbaru ");

        btnAutoRefresh.setBackground(new java.awt.Color(51, 255, 153));
        btnAutoRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAutoRefresh.setText("Auto Refresh");
        btnAutoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoRefreshActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnAutoRefresh)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoRefresh))
                .addGap(33, 33, 33)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 500, 240));

        txtInputRFID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInputRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputRFIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtInputRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 390, -1));

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoRefreshActionPerformed
        // TODO add your handling code here:
        // 1. Bersihkan semua kartu log absensi dari jPanel11
        jPanel11.removeAll();
        
        // 2. Segarkan tampilan UI agar langsung terlihat kosong kembali
        jPanel11.revalidate();
        jPanel11.repaint();
        
        // 3. Kembalikan fokus kursor ke input RFID agar siap menerima scan kartu baru
        txtInputRFID.setText("");
        txtInputRFID.requestFocus();
        
        // 4. Munculkan notifikasi singkat di pojok layar (opsional)
        System.out.println("Log tampilan absensi berhasil dibersihkan.");
    }//GEN-LAST:event_btnAutoRefreshActionPerformed

    private void txtInputRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputRFIDActionPerformed
    String rfidInput = txtInputRFID.getText().trim();
    if (rfidInput.isEmpty()) return;

    // Gunakan I18nService untuk teks default
    jLabel2.setForeground(java.awt.Color.BLACK);
    jLabel2.setText(swing.I18nService.get("lbl.kiosk.prompt"));

    try {
        services.MahasiswaService mService = new services.MahasiswaService();
        services.LogAbsensiService logService = new services.LogAbsensiService();
        objects.mahasiswa m = mService.cariMahasiswaSpesifikUID(rfidInput);
        
        String modeAbsen = services.LogAbsensiService.getStatusSistemAktif();

        if (m != null) {
            String nimDecrypted = util.EncryptionUtils.decrypt(m.getNimMahasiswa());
            
            // 1. Cek apakah sudah absen
            if (logService.sudahAbsenHariIni(rfidInput, modeAbsen)) {
                jLabel2.setForeground(new java.awt.Color(220, 53, 69)); 
                
                // Terjemahkan status (Masuk/Pulang) untuk pesan
                String statusKey = modeAbsen.equalsIgnoreCase("Pulang") ? "status.db.pulang" : "status.db.masuk";
                String modeTerjemahan = swing.I18nService.get(statusKey).toLowerCase();
                
                // Gunakan MessageFormat agar urutan bahasa tetap benar
                String template = swing.I18nService.get("msg.kiosk.already.scanned");
                String pesan = java.text.MessageFormat.format(template, m.getNama(), modeTerjemahan);
                
                jLabel2.setText(pesan);
            } else {
                // Simpan data log
                logService.simpanLog(rfidInput, java.time.LocalDateTime.now(), java.time.LocalDate.now(), m.getNama(), modeAbsen);

                // Panggil kartu log
                appendLogAbsensi(rfidInput, m.getNama(), nimDecrypted, m.getKelas(), modeAbsen);

                // Perbaikan: Gunakan I18nService + MessageFormat
                jLabel2.setForeground(new java.awt.Color(40, 167, 69)); 

                // Ambil template pesan: "Absen {0} berhasil: {1}"
                String template = swing.I18nService.get("msg.kiosk.success");

                // Terjemahkan status "Masuk"/"Pulang" agar muncul "Vào"/"Ra"
                String statusKey = modeAbsen.equalsIgnoreCase("Pulang") ? "status.db.pulang" : "status.db.masuk";
                String modeTerjemahan = swing.I18nService.get(statusKey);

                // Masukkan ke template
                String pesanSukses = java.text.MessageFormat.format(template, modeTerjemahan, m.getNama());
                jLabel2.setText(pesanSukses);
            }
        } else {
            // 5. Kartu Tidak Dikenal
            appendLogAbsensi(rfidInput, "TIDAK DIKENAL", "-----", "-", "Belum Terdaftar");
            jLabel2.setForeground(java.awt.Color.RED);
            jLabel2.setText(swing.I18nService.get("msg.kiosk.not.found"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    txtInputRFID.setText("");
    txtInputRFID.requestFocus();
    }//GEN-LAST:event_txtInputRFIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRFID;
    private javax.swing.JTextField txtInputRFID;
    // End of variables declaration//GEN-END:variables
    private swing.SlidingStatusToggle slidingStatusToggle1;
    
    private void thread1() {
        DigitalClockService service = new DigitalClockService(jLabel1, "EEEE, d MMMM yyyy, HH:mm:ss");
        clockThread1 = service.getThread();
        clockThread1.setName("Thread-Jam-Kiosk2");
        clockThread1.setDaemon(true);
        clockThread1.start();
    }
    
    public void appendLogAbsensi(String rfid, String nama, String nim, String kelas, String status) {
    jPanel11.removeAll();

        javax.swing.JPanel cardLog = new javax.swing.JPanel(new java.awt.BorderLayout(15, 0));
        cardLog.setBackground(java.awt.Color.WHITE);
        cardLog.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 1, true),
                javax.swing.BorderFactory.createEmptyBorder(12, 15, 12, 15)
        ));
        cardLog.setMaximumSize(new java.awt.Dimension(840, 95)); 

        javax.swing.JLabel lblFotoDefault = new javax.swing.JLabel();
        lblFotoDefault.setPreferredSize(new java.awt.Dimension(80, 70));
        lblFotoDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        try {
            lblFotoDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/card2.png"))); 
        } catch (Exception e) {
            lblFotoDefault.setOpaque(true);
            lblFotoDefault.setBackground(new java.awt.Color(0, 102, 153)); 
        }
        cardLog.add(lblFotoDefault, java.awt.BorderLayout.WEST);

        javax.swing.JPanel pnlInfo = new javax.swing.JPanel();
        pnlInfo.setBackground(java.awt.Color.WHITE);
        pnlInfo.setLayout(new javax.swing.BoxLayout(pnlInfo, javax.swing.BoxLayout.Y_AXIS));

        // 1. Label Nama
        javax.swing.JLabel lblNama = new javax.swing.JLabel(swing.I18nService.get("card.lbl.nama") + " : " + 
                                    (nama.equals("TIDAK DIKENAL") ? swing.I18nService.get("lbl.prof.unknown") : nama));
        lblNama.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // 2. Label NIM
        javax.swing.JLabel lblNim = new javax.swing.JLabel(swing.I18nService.get("card.lbl.nim") + " : " + nim);
        lblNim.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // 3. Label Kelas (Pastikan mengambil parameter 'kelas')
        javax.swing.JLabel lblKelas = new javax.swing.JLabel(swing.I18nService.get("card.lbl.kelas") + " : " + 
                                    (kelas == null || kelas.equals("Belum Terdaftar") ? swing.I18nService.get("status.db.unregistered") : kelas));
        lblKelas.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        pnlInfo.add(lblNama);
        pnlInfo.add(javax.swing.Box.createVerticalStrut(4)); 
        pnlInfo.add(lblNim);
        pnlInfo.add(javax.swing.Box.createVerticalStrut(4));
        pnlInfo.add(lblKelas);

        cardLog.add(pnlInfo, java.awt.BorderLayout.CENTER);

        // 4. Label Status (Pojok Kanan - Terjemahan Dinamis)
        String statusTranslate = status.equalsIgnoreCase("Pulang") ? 
                             swing.I18nService.get("status.db.pulang") : 
                             (status.equalsIgnoreCase("Masuk") ? swing.I18nService.get("status.db.masuk") : status);

        javax.swing.JLabel lblStatus = new javax.swing.JLabel(statusTranslate.toUpperCase(), javax.swing.SwingConstants.RIGHT);
        lblStatus.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        if (status.equalsIgnoreCase("Pulang")) {
            lblStatus.setForeground(new java.awt.Color(220, 53, 69)); // Merah
        } else {
            lblStatus.setForeground(new java.awt.Color(40, 167, 69)); // Hijau
        }
        cardLog.add(lblStatus, java.awt.BorderLayout.EAST);

        jPanel11.add(cardLog);
        jPanel11.revalidate();
        jPanel11.repaint();

        // Timer untuk mereset tampilan
        javax.swing.Timer timerSembunyi = new javax.swing.Timer(4000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jPanel11.removeAll();
                jPanel11.revalidate();
                jPanel11.repaint();
                jLabel2.setForeground(java.awt.Color.BLACK);
                jLabel2.setText(swing.I18nService.get("lbl.kiosk.prompt"));
            }
        });
        timerSembunyi.setRepeats(false); 
        timerSembunyi.start();
    }
}
