/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelAdmin;

/**
 *
 * @author ADVAN
 */
public class Dashboard extends javax.swing.JPanel {
    private final javax.swing.JPanel pnlLogDinamis = new javax.swing.JPanel();

    /**
     * Creates new form NewJPanel
     */
    public Dashboard() {
        initComponents();
        
        // 1. Format JSpinner ke tanggal Indonesia
        javax.swing.JSpinner.DateEditor editor = new javax.swing.JSpinner.DateEditor(jSpinner1, "dd-MM-yyyy");
        jSpinner1.setEditor(editor);
        
        // 2. Setup kontainer log di dalam JScrollPane1
        pnlLogDinamis.setLayout(new javax.swing.BoxLayout(pnlLogDinamis, javax.swing.BoxLayout.Y_AXIS));
        pnlLogDinamis.setBackground(java.awt.Color.WHITE);
        jScrollPane1.setViewportView(pnlLogDinamis);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        
        // 3. Listener saat tanggal spinner berubah
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sinkronisasiSeluruhDashboard();
            }
        });
        
        // Load data pertama kali
        sinkronisasiSeluruhDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbltotalmahasiswa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblhadirharian = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblterlambat = new javax.swing.JLabel();
        pnlGrafikmingguan = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbltidakabsen = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlGrafikmingguan1 = new javax.swing.JPanel();

        jPanel1.setPreferredSize(new java.awt.Dimension(887, 685));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(202, 255, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total Mahasiswa");

        lbltotalmahasiswa.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbltotalmahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltotalmahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltotalmahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(202, 255, 241));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hadir hari ini ");

        lblhadirharian.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblhadirharian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhadirharian, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhadirharian, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jPanel4.setBackground(new java.awt.Color(202, 255, 241));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Terlambat");

        lblterlambat.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblterlambat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblterlambat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblterlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        pnlGrafikmingguan.setBackground(new java.awt.Color(153, 255, 204));
        pnlGrafikmingguan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnlGrafikmingguan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 620, 270));

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Grafik Kehadiran Mingguan");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 620, 50));

        jPanel6.setBackground(new java.awt.Color(202, 255, 241));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tidak Absen");

        lbltidakabsen.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbltidakabsen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltidakabsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltidakabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jPanel8.setBackground(new java.awt.Color(153, 255, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Activity Terbaru");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 290, 50));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/tanggal.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, 30));

        pnlGrafikmingguan1.setBackground(new java.awt.Color(153, 255, 204));
        pnlGrafikmingguan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(pnlGrafikmingguan1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 290, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblhadirharian;
    private javax.swing.JLabel lblterlambat;
    private javax.swing.JLabel lbltidakabsen;
    private javax.swing.JLabel lbltotalmahasiswa;
    private javax.swing.JPanel pnlGrafikmingguan;
    private javax.swing.JPanel pnlGrafikmingguan1;
    // End of variables declaration//GEN-END:variables
private void sinkronisasiSeluruhDashboard() {
        if (jSpinner1.getValue() == null) return;
        
        try {
            dao.GenericDAO<objects.mahasiswa> mDAO = new dao.GenericDAO<>("mahasiswa", objects.mahasiswa.class);
            dao.GenericDAO<objects.logabsensi> logDAO = new dao.GenericDAO<>("log_absensi", objects.logabsensi.class);
            
            // 1. Hitung total mahasiswa
            java.util.List<objects.mahasiswa> semuaMhs = mDAO.findAll();
            long totalMhs = (semuaMhs != null) ? semuaMhs.size() : 0;
            lbltotalmahasiswa.setText(String.valueOf(totalMhs));
            
            // 2. Filter Tanggal Hari Ini untuk MongoDB
            java.util.Date dateSelected = (java.util.Date) jSpinner1.getValue();
            java.time.LocalDate lokalTgl = dateSelected.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            java.util.Date startHari = java.util.Date.from(lokalTgl.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());
            java.util.Date endHari = java.util.Date.from(lokalTgl.atTime(23, 59, 59).atZone(java.time.ZoneId.systemDefault()).toInstant());
            
            org.bson.conversions.Bson filterHariIni = com.mongodb.client.model.Filters.and(
                com.mongodb.client.model.Filters.gte("tanggal", startHari),
                com.mongodb.client.model.Filters.lte("tanggal", endHari)
            );
            java.util.List<objects.logabsensi> logHariTerpilih = logDAO.findMany(filterHariIni);
            
            // 3. Hitung Statistik Box Atas
            long totalHadir = 0, totalTerlambat = 0;
            if (logHariTerpilih != null) {
                for (objects.logabsensi log : logHariTerpilih) {
                    if (log.getStatus().equalsIgnoreCase("Tepat Waktu")) totalHadir++;
                    else if (log.getStatus().startsWith("Terlambat")) totalTerlambat++;
                }
            }
            long tidakAbsen = totalMhs - (totalHadir + totalTerlambat);
            if (tidakAbsen < 0) tidakAbsen = 0;
            
            lblhadirharian.setText(String.valueOf(totalHadir));
            lblterlambat.setText(String.valueOf(totalTerlambat));
            lbltidakabsen.setText(String.valueOf(tidakAbsen));
            
            // 4. Render Log Aktivitas Terbaru (Nama & Status Saja)
            pnlLogDinamis.removeAll();
            if (logHariTerpilih != null && !logHariTerpilih.isEmpty()) {
                logHariTerpilih.sort((l1, l2) -> l2.getWaktu().compareTo(l1.getWaktu())); // Terbaru di atas
                
                int counter = 0;
                for (objects.logabsensi log : logHariTerpilih) {
                    if (counter >= 6) break; // Maksimal 6 baris
                    
                    javax.swing.JPanel rowCard = new javax.swing.JPanel(new java.awt.BorderLayout(10, 0));
                    rowCard.setBackground(java.awt.Color.WHITE);
                    rowCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                        javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(240, 240, 240)),
                        javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15)
                    ));
                    rowCard.setMaximumSize(new java.awt.Dimension(280, 45));
                    
                    javax.swing.JLabel lblNama = new javax.swing.JLabel(log.getNama());
                    lblNama.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                    
                    javax.swing.JLabel lblStatus = new javax.swing.JLabel(log.getStatus().toUpperCase());
                    lblStatus.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
                    lblStatus.setForeground(log.getStatus().contains("Terlambat") ? new java.awt.Color(220, 53, 69) : new java.awt.Color(40, 167, 69));
                    
                    rowCard.add(lblNama, java.awt.BorderLayout.WEST);
                    rowCard.add(lblStatus, java.awt.BorderLayout.EAST);
                    pnlLogDinamis.add(rowCard);
                    counter++;
                }
                pnlLogDinamis.setPreferredSize(new java.awt.Dimension(0, counter * 45));
            } else {
                pnlLogDinamis.add(new javax.swing.JLabel(" Belum ada aktivitas scan harian."));
            }
            
            // 5. Render Grafik Batang
            tampilkanGrafikBatang(totalHadir, totalTerlambat, tidakAbsen);
            
            // Refresh Frame Grafis
            pnlLogDinamis.revalidate(); pnlLogDinamis.repaint();
            jScrollPane1.revalidate(); jScrollPane1.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
private void tampilkanGrafikBatang(long hadir, long terlambat, long alpa) {
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
        dataset.setValue(hadir, "Mahasiswa", "Tepat Waktu");
        dataset.setValue(terlambat, "Mahasiswa", "Terlambat");
        dataset.setValue(alpa, "Mahasiswa", "Tidak Absen");
        
        org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createBarChart(
                null, "Kategori Status", "Jumlah Orang", dataset,
                org.jfree.chart.plot.PlotOrientation.VERTICAL, false, true, false
        );
        
        // Desain Kosmetik Grafik Batang
        org.jfree.chart.plot.CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setRangeGridlinePaint(new java.awt.Color(230, 230, 230));
        
        org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new java.awt.Color(51, 204, 153)); // Hijau Pastel
        
        org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(pnlGrafikmingguan.getWidth(), pnlGrafikmingguan.getHeight()));
        
        pnlGrafikmingguan.removeAll();
        pnlGrafikmingguan.setLayout(new java.awt.BorderLayout());
        pnlGrafikmingguan.add(chartPanel, java.awt.BorderLayout.CENTER);
        pnlGrafikmingguan.revalidate();
        pnlGrafikmingguan.repaint();
    }
}
