/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PanelAdmin; 

import PanelAdmin.Dashboard;
import PanelAdmin.DataMahasiswa;
import PanelAdmin.DataDosen;
import PanelAdmin.Kehadiran;
import PanelAdmin.Pengaturan;
import PanelAdmin.Absensi;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import swing.SlidingStatusToggle;
/**
 *
 * @author ADVAN
 */
public class DashboardAdmin extends javax.swing.JFrame implements swing.I18nService.I18nChangeListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());
    private SlidingStatusToggle slidingStatusToggle1;

    /**
     * Creates new form Adminabsensi
     */
    public DashboardAdmin() {
        initComponents();
        // DAFTARKAN FRAME INI KE SERVICE
        swing.I18nService.registerListener(this);
        // Jalankan translasi pertama kali saat aplikasi dibuka
        onLanguageChanged();
        AddViews(new Dashboard());
    }
    public void onLanguageChanged() {
        jLabel12.setText(swing.I18nService.get("lbl.admin.system"));
        jLabel11.setText(swing.I18nService.get("lbl.admin.slogan"));
        
        btnDash.setText(swing.I18nService.get("btn.menu.dashboard"));
        btnAbs.setText(swing.I18nService.get("btn.menu.absensi"));
        btnMahasiswa.setText(swing.I18nService.get("btn.menu.mahasiswa"));
        btnDosen.setText(swing.I18nService.get("btn.menu.dosen"));
        btnLapo.setText(swing.I18nService.get("btn.menu.laporan"));
        btnSetting.setText(swing.I18nService.get("btn.menu.pengaturan"));
        jButton19.setText(swing.I18nService.get("btn.menu.profile"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnDash = new javax.swing.JButton();
        btnAbs = new javax.swing.JButton();
        btnMahasiswa = new javax.swing.JButton();
        btnDosen = new javax.swing.JButton();
        btnLapo = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 248, 221));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1020));
        jPanel1.setPreferredSize(new java.awt.Dimension(1555, 1087));

        jPanel4.setBackground(new java.awt.Color(47, 59, 51));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gemini_Generated_Image_swi19zswi19zswi1 (1) (2).png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SEMANGGI");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(214, 248, 221));
        jLabel11.setText("Mahasiswa Canggih");

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(214, 248, 221));
        jLabel12.setText("Sistem Absensi");

        btnDash.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        btnDash.setText("Dashboard");
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDash.setIconTextGap(10);
        btnDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashActionPerformed(evt);
            }
        });

        btnAbs.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnAbs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rfid.png"))); // NOI18N
        btnAbs.setText("Absensi");
        btnAbs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbs.setIconTextGap(10);
        btnAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsActionPerformed(evt);
            }
        });

        btnMahasiswa.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student.png"))); // NOI18N
        btnMahasiswa.setText("Data Mahasiswa");
        btnMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMahasiswa.setIconTextGap(10);
        btnMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMahasiswaActionPerformed(evt);
            }
        });

        btnDosen.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnDosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dosen.png"))); // NOI18N
        btnDosen.setText("Data Dosen");
        btnDosen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDosen.setIconTextGap(10);
        btnDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosenActionPerformed(evt);
            }
        });

        btnLapo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnLapo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report.png"))); // NOI18N
        btnLapo.setText("Laporan");
        btnLapo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapo.setIconTextGap(10);
        btnLapo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapoActionPerformed(evt);
            }
        });

        btnSetting.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setting.png"))); // NOI18N
        btnSetting.setText("Pengaturan");
        btnSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSetting.setIconTextGap(10);
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMahasiswa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(btnDosen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLapo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)))
                .addGap(105, 105, 105)
                .addComponent(btnDash)
                .addGap(30, 30, 30)
                .addComponent(btnAbs)
                .addGap(29, 29, 29)
                .addComponent(btnMahasiswa)
                .addGap(32, 32, 32)
                .addComponent(btnDosen)
                .addGap(30, 30, 30)
                .addComponent(btnLapo)
                .addGap(29, 29, 29)
                .addComponent(btnSetting)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(214, 248, 221));

        jButton19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/user.png"))); // NOI18N
        jButton19.setText("Admin");
        jButton19.setIconTextGap(10);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/notif.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/pesan.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(937, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addComponent(jButton19)
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
        // TODO add your handling code here:
        AddViews(new Dashboard());
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsActionPerformed
        // TODO add your handling code here:
        AddViews(new Absensi());
    }//GEN-LAST:event_btnAbsActionPerformed

    private void btnDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosenActionPerformed
        // TODO add your handling code here:
        AddViews(new DataDosen());
    }//GEN-LAST:event_btnDosenActionPerformed

    private void btnLapoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapoActionPerformed
        // TODO add your handling code here:
        AddViews(new Kehadiran());
    }//GEN-LAST:event_btnLapoActionPerformed

    private void btnMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMahasiswaActionPerformed
        // TODO add your handling code here:
        AddViews(new DataMahasiswa());
    }//GEN-LAST:event_btnMahasiswaActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        AddViews(new Pengaturan());
    }//GEN-LAST:event_btnSettingActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
// TODO add your handling code here:
        // KOREKSI UTAMA: Arahkan ke PanelAdmin.Login.dosenAktif agar datanya terpanggil!
        objects.dosen dosenSesi = PanelAdmin.Login.dosenAktif; 

        // 2. Buat instance dari panel profile dengan mengirimkan data dosen aktif
        dialogs.profile pnlProfile = new dialogs.profile(dosenSesi);

        // 3. Bungkus panel ke dalam JDialog standar Swing agar muncul sebagai popup dialog
        javax.swing.JDialog dialog = new javax.swing.JDialog((javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), "Profil Pengguna", true);
        dialog.getContentPane().add(pnlProfile);
        dialog.pack();
        dialog.setLocationRelativeTo(this); 
        dialog.setResizable(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbs;
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnDosen;
    private javax.swing.JButton btnLapo;
    private javax.swing.JButton btnMahasiswa;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

     private void AddViews(JPanel P){
        if(jPanel2.getComponentCount() > 0){
            jPanel2.removeAll();
        }
        jPanel2.add(P, BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }
public swing.SlidingStatusToggle getSlidingStatusToggle1() {
    return slidingStatusToggle1; 
    // Ganti 'slidingStatusToggle1' sesuai dengan nama variabel toggle yang ada di menu Pengaturan Anda
}
// Taruh ini di dalam class utama (misal MainFrame atau DashboardAdmin) agar bisa dipanggil secara global
public static objects.dosen dosenAktif;
}
