/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelAdmin;

/**
 *
 * @author ADVAN
 */
public class Kehadiran extends javax.swing.JPanel implements swing.I18nService.I18nChangeListener {
    /**
     * Creates new form Kehadiran
     */
    public Kehadiran() {
        initComponents();
        
        // 1. Format visual JSpinner
        javax.swing.JSpinner.DateEditor editor1 = new javax.swing.JSpinner.DateEditor(jSpinner1, "dd-MM-yyyy");
        jSpinner1.setEditor(editor1);
        
        javax.swing.JSpinner.DateEditor editor2 = new javax.swing.JSpinner.DateEditor(jSpinner2, "dd-MM-yyyy");
        jSpinner2.setEditor(editor2);
        
        // 2. Setup Layout Kontainer (Gunakan batasan biar rapi)
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
        
        // 3. Jalankan pemuatan data awal
        sinkronisasiStatistikDashboard();
        eksekusiFilterLaporan();
        
        // 4. Paksa UI untuk menggambar ulang di awal agar data langsung nongol
        this.revalidate();
        this.repaint();
        // DAFTARKAN PANEL INI
        swing.I18nService.registerListener(this);   
        onLanguageChanged();
    }

    private void eksekusiFilterLaporan() {
        if (jSpinner1.getValue() != null && jSpinner2.getValue() != null) {
            java.util.Date dateMulai = (java.util.Date) jSpinner1.getValue();
            java.util.Date dateSelesai = (java.util.Date) jSpinner2.getValue();
            
            // Konversi java.util.Date ke java.time.LocalDate
            java.time.LocalDate tglMulai = dateMulai.toInstant()
                    .atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            java.time.LocalDate tglSelesai = dateSelesai.toInstant()
                    .atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            
            // Jalankan query filter ke database
            muatLaporanBerdasarkanTanggal(tglMulai, tglSelesai);
        }
    }
    public void onLanguageChanged() {
        jLabel1.setText(swing.I18nService.get("lbl.rpt.total.scan"));
        jLabel3.setText(swing.I18nService.get("lbl.rpt.hadir"));
        jLabel5.setText(swing.I18nService.get("lbl.rpt.pulang"));
        jLabel6.setText(swing.I18nService.get("lbl.rpt.tidak.hadir"));
        jLabel10.setText(swing.I18nService.get("lbl.rpt.range"));
        jLabel7.setText(swing.I18nService.get("lbl.rpt.log.title"));
        btnAutoRefresh4.setText(swing.I18nService.get("btn.rpt.refresh"));
        
        // Segarkan database agar isian teks di dalam kartu log laporan ikut terjemah
        eksekusiFilterLaporan();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblscan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblhadir = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblterlambat = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbltidakhadir = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAutoRefresh4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(202, 255, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total Scan");

        lblscan.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblscan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblscan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblscan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(202, 255, 241));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hadir");

        lblhadir.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblhadir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(202, 255, 241));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Terlambat");

        lblterlambat.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblterlambat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblterlambat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblterlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(202, 255, 241));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tidak Hadir");

        lbltidakhadir.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbltidakhadir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltidakhadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltidakhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 255, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Log Seluruh Scan RFID");

        btnAutoRefresh4.setBackground(new java.awt.Color(51, 255, 153));
        btnAutoRefresh4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAutoRefresh4.setText("Auto Refresh");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAutoRefresh4)
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoRefresh4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/tanggal.png"))); // NOI18N

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("S/D");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon/tanggal.png"))); // NOI18N

        jSpinner2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerDateModel());
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSpinner2)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        eksekusiFilterLaporan();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        eksekusiFilterLaporan();
    }//GEN-LAST:event_jSpinner2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoRefresh4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblhadir;
    private javax.swing.JLabel lblscan;
    private javax.swing.JLabel lblterlambat;
    private javax.swing.JLabel lbltidakhadir;
    // End of variables declaration//GEN-END:variables
public void sinkronisasiStatistikDashboard() {
        try {
            dao.GenericDAO<objects.mahasiswa> mDAO = new dao.GenericDAO<>("mahasiswa", objects.mahasiswa.class);
            dao.GenericDAO<objects.logabsensi> logDAO = new dao.GenericDAO<>("log_absensi", objects.logabsensi.class);
            
            java.util.List<objects.mahasiswa> semuaMhs = mDAO.findAll();
            long totalMhs = (semuaMhs != null) ? semuaMhs.size() : 0;
            
            java.time.LocalDate hariIni = java.time.LocalDate.now();
            
            // KOREKSI FILTER: Mencari status real "Masuk" hari ini
            org.bson.conversions.Bson filterHadir = com.mongodb.client.model.Filters.and(
                com.mongodb.client.model.Filters.eq("tanggal", hariIni),
                com.mongodb.client.model.Filters.eq("status", "Masuk")
            );
            java.util.List<objects.logabsensi> listHadir = logDAO.findMany(filterHadir);
            long totalHadir = (listHadir != null) ? listHadir.size() : 0;
            
            // KOREKSI FILTER: Mencari status real "Pulang" hari ini
            org.bson.conversions.Bson filterTerlambat = com.mongodb.client.model.Filters.and(
                com.mongodb.client.model.Filters.eq("tanggal", hariIni),
                com.mongodb.client.model.Filters.eq("status", "Pulang")
            );
            java.util.List<objects.logabsensi> listTerlambat = logDAO.findMany(filterTerlambat);
            long totalTerlambat = (listTerlambat != null) ? listTerlambat.size() : 0;
            
            long tidakAbsen = totalMhs - totalHadir;
            if (tidakAbsen < 0) tidakAbsen = 0;
            
            lblhadir.setText(String.valueOf(totalHadir));
            lblterlambat.setText(String.valueOf(totalTerlambat));
            lbltidakhadir.setText(String.valueOf(tidakAbsen));
            
        } catch (Exception e) {
            System.out.println("Gagal memuat statistik dashboard harian: " + e.getMessage());
        }
    }

    public void muatLaporanBerdasarkanTanggal(java.time.LocalDate tglMulai, java.time.LocalDate tglSelesai) {
        try {
        dao.GenericDAO<objects.logabsensi> logDAO = new dao.GenericDAO<>("log_absensi", objects.logabsensi.class);
        
        java.util.Date dateMulai = java.util.Date.from(tglMulai.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());
        java.util.Date dateSelesai = java.util.Date.from(tglSelesai.atTime(23, 59, 59).atZone(java.time.ZoneId.systemDefault()).toInstant());
        
        org.bson.conversions.Bson filterJangkauan = com.mongodb.client.model.Filters.and(
            com.mongodb.client.model.Filters.gte("waktu", dateMulai),
            com.mongodb.client.model.Filters.lte("waktu", dateSelesai)
        );
        
        java.util.List<objects.logabsensi> daftarLog = logDAO.findMany(filterJangkauan);
        
        long scanCount = 0;
        long hadirCount = 0;
        long lambatCount = 0;
        long alpaCount = 0;
        
        jPanel11.removeAll(); 
        
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
        if (daftarLog != null && !daftarLog.isEmpty()) {
            daftarLog.sort((log1, log2) -> {
                if (log1.getWaktu() == null || log2.getWaktu() == null) return 0;
                return log2.getWaktu().compareTo(log1.getWaktu());
            });
            
            java.time.format.DateTimeFormatter tglFormat = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");
            
            for (objects.logabsensi log : daftarLog) {
                scanCount++;
                
                if (log.getStatus().equalsIgnoreCase("Masuk")) {
                    hadirCount++;
                } else if (log.getStatus().equalsIgnoreCase("Pulang")) {
                    lambatCount++;
                } else if (log.getStatus().equalsIgnoreCase("Tidak Hadir")) {
                    alpaCount++;
                }
                
                String jamAbsen = "--:--";
                if (log.getWaktu() != null) {
                    jamAbsen = log.getWaktu().format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"));
                }
                
                String stringTanggal = log.getTanggal().format(tglFormat);
                
                // LOGIKA TERJEMAHAN STATUS BARU
                String statusLog = log.getStatus();
                String statusKey = statusLog.equalsIgnoreCase("Pulang") ? "status.db.pulang" : 
                                  (statusLog.equalsIgnoreCase("Tidak Hadir") ? "lbl.rpt.tidak.hadir" : "status.db.masuk");
                String statusTeks = swing.I18nService.get(statusKey);
                
                javax.swing.JPanel wrapperCard = new javax.swing.JPanel();
                wrapperCard.setLayout(new java.awt.BorderLayout());
                wrapperCard.setOpaque(false);
                wrapperCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 10, 20));
                wrapperCard.setMaximumSize(new java.awt.Dimension(1019, 75)); 
                
                javax.swing.JPanel rowCard = new javax.swing.JPanel();
                rowCard.setLayout(new java.awt.BorderLayout(15, 0));
                rowCard.setBackground(java.awt.Color.WHITE);
                rowCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(220, 235, 230)),
                    javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20)
                ));
                
                javax.swing.JPanel leftPanel = new javax.swing.JPanel();
                leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.Y_AXIS));
                leftPanel.setBackground(java.awt.Color.WHITE);
                
                javax.swing.JLabel lblNama = new javax.swing.JLabel(log.getNama());
                lblNama.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
                lblNama.setForeground(new java.awt.Color(40, 40, 40));
                
                javax.swing.JLabel lblDetail = new javax.swing.JLabel("Tanggal: " + stringTanggal + "   |   Jam: " + jamAbsen);
                lblDetail.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
                lblDetail.setForeground(java.awt.Color.GRAY);
                
                leftPanel.add(lblNama);
                leftPanel.add(javax.swing.Box.createVerticalStrut(2));
                leftPanel.add(lblDetail);
                
                // MENGGUNAKAN STATUS TERJEMAHAN
                javax.swing.JLabel lblBadgeStatus = new javax.swing.JLabel("  " + statusTeks.toUpperCase() + "  ");
                lblBadgeStatus.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));
                lblBadgeStatus.setOpaque(true);
                lblBadgeStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                
                if (log.getStatus().equalsIgnoreCase("Pulang")) {
                    lblBadgeStatus.setBackground(new java.awt.Color(255, 230, 230));
                    lblBadgeStatus.setForeground(new java.awt.Color(200, 0, 0));
                } else if (log.getStatus().equalsIgnoreCase("Tidak Hadir")) {
                    lblBadgeStatus.setBackground(java.awt.Color.LIGHT_GRAY);
                    lblBadgeStatus.setForeground(java.awt.Color.DARK_GRAY);
                } else {
                    lblBadgeStatus.setBackground(new java.awt.Color(230, 245, 235));
                    lblBadgeStatus.setForeground(new java.awt.Color(0, 130, 40));
                }
                
                rowCard.add(leftPanel, java.awt.BorderLayout.WEST);
                rowCard.add(lblBadgeStatus, java.awt.BorderLayout.EAST);
                
                wrapperCard.add(rowCard, java.awt.BorderLayout.CENTER);
                jPanel11.add(wrapperCard);
            }
            
            int totalTinggiPanel = daftarLog.size() * 85; 
            jPanel11.setPreferredSize(new java.awt.Dimension(jPanel7.getWidth() - 30, totalTinggiPanel));
            
        } else {
            javax.swing.JPanel emptyCard = new javax.swing.JPanel();
            emptyCard.setOpaque(false);
            // MENGGUNAKAN PESAN DINAMIS
            emptyCard.add(new javax.swing.JLabel(swing.I18nService.get("lbl.rpt.empty"))); 
            jPanel11.add(emptyCard);
        }
        
        lblscan.setText(String.valueOf(scanCount));
        lblhadir.setText(String.valueOf(hadirCount));
        lblterlambat.setText(String.valueOf(lambatCount));
        lbltidakhadir.setText(String.valueOf(alpaCount));
        
        jPanel11.revalidate();
        jPanel11.repaint();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
}
